### ISSUE TITLE
Categoryテーブルについて

### ISSUE THREAD

**Issue by Yuri-Kosaki** [THitokuse/mercari#20]
現在の中間テーブル(item_categories)を使用したアソシエーションだと、本物のメルカリのような1つのカテゴリに複数のカテゴリが入っていて、その中にもまた複数のカテゴリを実装するのが困難なので、テーブルとアソシエーションを少し変えようと思います。

<img width="1280" alt="2019-02-19 19 56 54" src="https://user-images.githubusercontent.com/24793349/53010663-ce6a2880-3481-11e9-9a06-4bc1be8b6ae1.png">

## upper_categoriesテーブル
- 大枠のカテゴリテーブル

column | type | options
------ | ---- | ------- 
id |integer |AI Primary key
name | varchar(255) | null: false
- has_many :items
- has_many :middle_categories

## middle_categoriesテーブル
- 中枠のカテゴリテーブル

column | type | options
------ | ---- | ------- 
id |integer |AI Primary key
name | varchar(255) | null: false
upper_category | reference | null: false, foreign_key: true
size_type | reference | null: false, foreign_key: true

- has_many :items
- has_many :lower_categories
- belongs_to :upper_category
- belongs_to :size_type

## lower_categoriesテーブル
- 小枠のカテゴリテーブル

column | type | options
------ | ---- | ------- 
id |integer |AI Primary key
name | varchar(255) | null: false
middle_category | reference | null: false, foreign_key true

- belongs_to :middle_category
- has_many :items

## size_typeテーブル
- サイズの種類を表すテーブル

column | type | options
------ | ---- | ------- 
id |integer |AI Primary key
size_type | varchar(255) | null: false

- has_many :sizes
- has_many :middle_categories

## sizeテーブル
- 商品のサイズの単位を表すテーブル

column | type | options
------ | ---- | ------- 
id |integer |AI Primary key
name | varchar(255) | null: false
size_type | reference | null: false, foreign_key true

- has_many :items
- belongs_to :size_type

# 追加
## itemテーブル

column | type | options
------ | ---- | ------- 
upper_category | reference | null: false, foreign_key true
middle_category | reference | null: false, foreign_key true
lower_category | reference | null: false, foreign_key true
size | reference | null: false, foreign_key true

**Comment by THitokuse** [comment]
approved

**Comment by THitokuse** [comment]
@Yuri-Kosaki 
時間があればREADMEも変更お願いします。

**Comment by Yuri-Kosaki** [comment]
@THitokuse 
了解です。
